import type { PropsWithChildren } from "react";

import HomeLayout from "~/app/layouts/home-layout/home-layout";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextJS starter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return <HomeLayout>{children}</HomeLayout>;
}
